Fix python3 Compatibility for hashlib md5 update
Without this change in Python3 it returns following:-
TypeError: Unicode-objects must be encoded before hashing

In Python3 encoding is explicitly needed, using encode method
or b"<string>" it can be achieved. Hashing examples with python([1])

[1] https://www.pythoncentral.io/hashing-strings-with-python/

Change-Id: I17ca99f00492633fa8e9e15558096792a48d204b