Don't pass debug option to websocket constructor
Now, if you try to run Zaqar on Websocket driver with fresh 'autobahn'
library, Zaqar will fail:
TypeError: __init__() got an unexpected keyword argument 'debug'

Websocket-related tests now fail too.

The 'debug' option for instantiating websocket WebSocketServerFactory
was deprecated and recently it was finally removed from 'autobahn'
library.

This patch makes Zaqar not pass 'debug' option to WebSocketServerFactory
constructor. The change will not affect logging and will just fix the
problem.

Change-Id: Ifebf849b278f95438ed87ca50ff8cc48ad159104
Closes-Bug: 1558062