The `subtype` formatting arg does not exist
The logging decorator was causing tracebacks due to a nonexistent formatting
argument.

```
Traceback (most recent call last):
  [snipped]
KeyError: u'subtype'
Logged from file decorators.py, line 45
```

Change-Id: I9299da8617c7e86a863feb0957f439b90dd60a6a