Some prerequisites for Ubuntu OS is missing in zaqar README.rst
At at the section "1. Install prerequisites:" in zaqar README.rst
python-dev, zlib1g-dev packages is not listed for Ubuntu OS.
These packages must be installed in the environment,otherwise
"tox -e genconfig" command will fail with below error.

ERROR: genconfig: could not install deps [-r/home/datanode1/try/zaqar
/requirements.txt

Change-Id: I6e0941cdd8b7d27149c9ef14270d37399a018a6d
Closes-bug: #1505911